# Generated by Django 2.0.5 on 2018-07-30 01:13

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activation',
            field=models.CharField(default=events.models.random_string, max_length=200),
        ),
    ]
