# Generated by Django 2.0.5 on 2018-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180731_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='location',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
