# Generated by Django 2.0.5 on 2018-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_playerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='status',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Maybe', 'Maybe'), ('Passing', 'Passing'), ('Awaiting', 'Awaiting Response')], default='Awaiting', max_length=20),
        ),
    ]
